# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - facerec

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Fix ESLint warnings
        working-directory: ./frontend
        run: |
          npm install --save-dev @typescript-eslint/eslint-plugin
          npx eslint --fix src/**/*.{ts,tsx}

      - name: Build frontend
        working-directory: ./frontend
        env:
          CI: false
          NODE_OPTIONS: --max_old_space_size=4096
          SKIP_PREFLIGHT_CHECK: true
        run: |
          echo "// @ts-ignore" > node_modules/face-api.js/build/es6/env/index.d.ts
          npm run build

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Build backend
        working-directory: ./backend
        run: npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: |
            frontend/build
            backend/dist
            backend/package.json
            backend/package-lock.json
            docker-compose.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_56D0095279904B018F9AD4DD7D073E49 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F48B2534D79847CDA960FF3A03844A3A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3E994E3E97134723BBD6235962B951C8 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'facerec'
          slot-name: 'Production'
          package: .
          