name: Build and deploy Node.js app to Azure Web App - FaceRec

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # === FRONTEND ===
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Set CI to false
        run: echo "CI=false" >> $GITHUB_ENV


      - name: Build React frontend
        working-directory: ./frontend
        run: npm run build

      # === BACKEND ===
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Build backend (TypeScript)
        working-directory: ./backend
        run: npm run build

      - name: Copy frontend build into backend dist
        run: cp -r ./frontend/build ./backend/dist/build

      - name: Zip artifact for deployment
        working-directory: ./backend/dist
        run: zip -r ../../release.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2E042CDDCBC1416A9F37175565541675 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D85C9AB67D484F22AC824EDD47D6CE17 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E2F93A80B3B641B68087377973699106 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FaceRec'
          slot-name: 'Production'
          package: .
